### PR TITLE
Bug Fix: CustomControls with multiple command lines and Control/Command Confirm handling.

### LINKED ISSUE #228: Custom Commands Don't Support Multiple Commands
The Custom Command list in the `Control` panel passes on Custom Commands that do not contain a `command` or `script` property:

https://github.com/Z-Bolt/OctoScreen/blob/7ef3c0277b084a9730210922b790372a2ec2c5d8/ui/ControlPanel.go#L84

However, by default, the `Control` Button *also* supports the `commands` property:

https://github.com/Z-Bolt/OctoScreen/blob/7ef3c0277b084a9730210922b790372a2ec2c5d8/uiWidgets/ControlButton.go#L51

It would make sense to include that as a property for adding.

**Additionally:**  Currently the upstream OctoPrint Custom Commands parser fails pretty bad with parsing `input` properties, which kind of saves OctoScreen, in that it does not support `input` either.  It may be beneficial to add a check that the Custom Command *does not* include any `input` properties, just in case the upstream library gets that fixed.

And finally, although I am not sure if these properties are supported upstream or not, but it may be beneficial to *also* filter out any Custom Controls with the properties `javascript` and/or `enabled`, as both of those properties are designed to run in-browser.  Maybe even `regex` and `template` too, as those are designed for rendering in-browser, and I don't see where there are provisions to render output to OctoScreen at this time...

### LINKED ISSUE #264: Bug: CommandButton and ControlButton do not handle commands with Confirm
This is just a note, fix is incoming in PR #263.

`func (this *${Type}Button) handleClicked()` generates, but does not call, the closure returned by `utils.MustConfirmDialogBox()`.

This is a relatively simple fix, I have it done, I am just waiting on a build to test and validate.

### PR DESCRIPTION
**Pull request by thebeline**
Well, I WAS testing this.  The build is fine, and it does populate the list with the Custom Control (NEW! NEAT!), but clicking does all of nothing.  So I am working to sort that out now.

Resolves #264 
Resolves #228

### CODE REVIEW

**Comment by thebeline** [comment]
NEAT, it was due to `confirm`, guess I will go ahead and see about fixing that, too...
:-D

**Comment by thebeline** [comment]
Confirmed, Validated, Tested.

Resolves: #264

File: ui/ControlPanel.go [hunk 1]
```diff
@@ -83,7 +83,7 @@ func (this *controlPanel) getCustomControls() []*dataModels.ControlDefinition {
 
 	for _, control := range response.Controls {
 		for _, childControl := range control.Children {
-			if childControl.Command != "" || childControl.Script != "" {
+			if childControl.Command != "" || childControl.Script != "" || childControl.Commands != nil {
```
Comment (JeffB42) [inline ui/ControlPanel.go:86]: 👍

File: uiWidgets/CommandButton.go [hunk 2]
```diff
@@ -41,20 +41,27 @@ func CreateCommandButton(
 }
 
 func (this *CommandButton) handleClicked() {
+	var handleClick func()
+	
 	if len(this.commandDefinition.Confirm) != 0 {
-		utils.MustConfirmDialogBox(this.parentWindow, this.commandDefinition.Confirm, this.sendCommand)
-		return
+		logger.Debugf("CommandButton.handleClicked().MustConfirmDialogBox: %s", this.commandDefinition.Name)
+		handleClick = utils.MustConfirmDialogBox(this.parentWindow, this.commandDefinition.Confirm, this.sendCommand)
```
Comment (JeffB42) [inline uiWidgets/CommandButton.go:48]: Seems like most of these changes aren't needed, and could have been fixed with just turning the call to MustConfirmDialogBox into an IIFE:
```
utils.MustConfirmDialogBox(this.parentWindow, this.commandDefinition.Confirm, this.sendCommand)()
```

I'm going to merge and close this PR and then clean up the changes here and in ControlButton up.

File: uiWidgets/ControlButton.go [hunk 3]
```diff
@@ -41,15 +41,22 @@ func CreateControlButton(
 }
 
 func (this *ControlButton) handleClicked() {
+	var handleClick func()
+	
 	if len(this.controlDefinition.Confirm) != 0 {
-		utils.MustConfirmDialogBox(this.parentWindow, this.controlDefinition.Confirm, this.sendCommand)
-		return
+		logger.Debugf("ControlButton.handleClicked().MustConfirmDialogBox: %s", this.controlDefinition.Name)
```
Comment (JeffB42) [inline uiWidgets/ControlButton.go:47]: Similar comment as about.

File: uiWidgets/CommandButton.go (hunk 2 above)
Comment (thebeline) [reply uiWidgets/CommandButton.go:48]: You aren't wrong, that being said, I (personally) prefer single-return logic, and since calling of `handleClick()` is essentially the return on this function, I went this route.  But you aren't wrong.  Your call.

File: uiWidgets/ControlButton.go (hunk 3 above)
Comment (thebeline) [reply uiWidgets/ControlButton.go:47]: Similar answer as about. ;-)
